In [1]:
import numpy as np
import pandas as pd

In [2]:
import numpy as np
data=np.loadtxt("C:/Users/Lenovo/Desktop/Jupyter Notebook/fitness.txt",dtype="str")


# Numpy 3

In [3]:
data.T

array([['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
        '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
        '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
        '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
        '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
        '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
        '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
        '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
        '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
        '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
        '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
        '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
        '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
        '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
        '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
        '05-12-2017', '06-12-2017', '07-

In [4]:
date,step_count,mood,calories_burned,hours_of_sleep,bool_of_active,weight_kg=data.T

In [5]:
step_count

array(['5464', '6041', '25', '5461', '6915', '4545', '4340', '1230', '61',
       '1258', '3148', '4687', '4732', '3519', '1580', '2822', '181',
       '3158', '4383', '3881', '4037', '202', '292', '330', '2209',
       '4550', '4435', '4779', '1831', '2255', '539', '5464', '6041',
       '4068', '4683', '4033', '6314', '614', '3149', '4005', '4880',
       '4136', '705', '570', '269', '4275', '5999', '4421', '6930',
       '5195', '546', '493', '995', '1163', '6676', '3608', '774', '1421',
       '4064', '2725', '5934', '1867', '3721', '2374', '2909', '1648',
       '799', '7102', '3941', '7422', '437', '1231', '1696', '4921',
       '221', '6500', '3575', '4061', '651', '753', '518', '5537', '4108',
       '5376', '3066', '177', '36', '299', '1447', '2599', '702', '133',
       '153', '500', '2127', '2203'], dtype='<U10')

In [6]:
#To change data type
step_count = np.array(step_count,dtype = "int")
step_count

array([5464, 6041,   25, 5461, 6915, 4545, 4340, 1230,   61, 1258, 3148,
       4687, 4732, 3519, 1580, 2822,  181, 3158, 4383, 3881, 4037,  202,
        292,  330, 2209, 4550, 4435, 4779, 1831, 2255,  539, 5464, 6041,
       4068, 4683, 4033, 6314,  614, 3149, 4005, 4880, 4136,  705,  570,
        269, 4275, 5999, 4421, 6930, 5195,  546,  493,  995, 1163, 6676,
       3608,  774, 1421, 4064, 2725, 5934, 1867, 3721, 2374, 2909, 1648,
        799, 7102, 3941, 7422,  437, 1231, 1696, 4921,  221, 6500, 3575,
       4061,  651,  753,  518, 5537, 4108, 5376, 3066,  177,   36,  299,
       1447, 2599,  702,  133,  153,  500, 2127, 2203])

In [7]:
np.average(step_count)

2935.9375

In [8]:
mood = np.array(mood,dtype = "int")
mood
calories_burned = np.array(calories_burned,dtype = "int")
calories_burned
hours_of_sleep = np.array(hours_of_sleep,dtype = "int")
hours_of_sleep
weight_kg = np.array(weight_kg,dtype = "int")
weight_kg

array([66, 66, 66, 66, 66, 66, 66, 66, 66, 65, 65, 65, 65, 65, 65, 65, 65,
       65, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
       64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
       64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
       64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64,
       64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64])

In [9]:
hours_of_sleep

array([5, 8, 5, 4, 5, 6, 6, 7, 5, 6, 8, 5, 6, 7, 5, 6, 8, 5, 4, 5, 6, 8,
       5, 6, 5, 8, 5, 4, 5, 4, 5, 4, 3, 2, 9, 5, 6, 4, 5, 8, 4, 5, 6, 5,
       6, 5, 6, 5, 6, 5, 6, 7, 6, 7, 6, 5, 6, 7, 8, 8, 7, 8, 5, 4, 3, 3,
       4, 5, 5, 5, 3, 4, 4, 5, 5, 5, 5, 5, 5, 4, 3, 4, 5, 5, 4, 5, 3, 3,
       3, 2, 3, 2, 8, 5, 5, 5])

In [10]:
mood = data.T[2,:]

mood[mood == "100"] = "Sad"
mood[mood == "200"] = "Neutral"
mood[mood == "300"] = "Happy"
mood

array(['Neutral', 'Sad', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Sad', 'Sad', 'Sad', 'Happy', 'Sad', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral',
       'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Neutral',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Sad', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Sad', 'Neutral', 'Neutral',
       'Sad', 'Sad', 'Neutral', 'Neutral', 'Happy', 'Neutral', 'Neutral',
       'Sad', 'Neutral', 'Sad', 'Neutral', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Happy', 'Neutral', 'Happy', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Sad', 'Sad', 'Happy', 'Neutral', 'Neutral',
       'Happy'], dtype='<U10')

In [11]:
bool_of_active[bool_of_active == "0"] = "Inactive"
bool_of_active[bool_of_active == "500"] = "Active"
bool_of_active

array(['Inactive', 'Inactive', 'Inactive', 'Inactive', 'Active',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Active', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Active', 'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Active',
       'Inactive', 'Inactive', 'Inactive', 'Inactive', 'Inactive',
       'Active', 'Active', 'Active', 'Active', 'Active', 'Active',
       'Active', 'Active', 'Active', 'Inactive', 'Inactive', 'Inactive',
       'Inactive', 'Inactive', 'Inactive', 'Active', 'Active', 'Active',
       'Active', 'Active', 'Active', 'Active', 'Active', 'Active',
       'Active', 'Active', 'Active', 'Inactive', 'Active', 'Active',
       'Inactive', 'Active', 'Active', 'Active', 'Active', 'Active',
       'Inactive', 'Active', 'Active', 'Active', 'Active', 'Inactive',
       'Inactive', 'Inactive', 'Inacti

In [12]:
np.unique(bool_of_active, return_counts = True )
np.unique(mood, return_counts = True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'),
 array([40, 27, 29], dtype=int64))

In [13]:
date[np.argmax(step_count)]

'14-12-2017'

In [14]:
calories_burned[np.argmax(step_count)]

243

In [15]:
np.unique(mood[step_count>4000], return_counts = True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'),
 array([22,  9,  7], dtype=int64))

In [16]:
np.unique(mood[hours_of_sleep<np.mean(hours_of_sleep)], return_counts = True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'),
 array([20, 24, 19], dtype=int64))

In [17]:
np.unique(bool_of_active[hours_of_sleep<4], return_counts = True)

(array(['Active', 'Inactive'], dtype='<U10'), array([3, 9], dtype=int64))

In [18]:
arr = np.array([-3,4,27,34,-2, 0, -45,-11,4, 0 ])
arr

array([ -3,   4,  27,  34,  -2,   0, -45, -11,   4,   0])

In [19]:
np.where(arr>= 0, 1, -1)

array([-1,  1,  1,  1, -1,  1, -1, -1,  1,  1])

In [20]:
a = np.arange(0,12).reshape(4,3)
b = np.arange(0,12).reshape(6,2)
print(a)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [21]:
np.dot(a,b)

ValueError: shapes (4,3) and (6,2) not aligned: 3 (dim 1) != 6 (dim 0)

# Numpy 4

In [ ]:
import math as m
import numpy as np
function = np.vectorize()
function([2,3,4])

In [ ]:
arr = [1,2,3]
def cube(arr):
    return arr**3
function= np.vectorize(cube)
function(arr)
cube(arr)

In [ ]:
a = np.arange(0,12).reshape(4,3)
a
b = a.T
a.flatten()

In [ ]:
np.shares_memory(a,b)

# Pandas -1

In [ ]:
import pandas as pd

In [ ]:
!pip install pandas

In [ ]:
df = pd.read_csv("C:/Users/Lenovo/Desktop/Jupyter Notebook/gapminder.csv")
df

In [ ]:
df[["country","year"]]

In [ ]:
df.iloc[:20]

In [ ]:
df1 = pd.DataFrame([["17","Mayank","95"],["18","Nishant","96"]],columns =["Roll no.","Name","Marks"])
df1

In [ ]:
pd.DataFrame?

In [ ]:
string = "How much wood would a woodchuck chuck if a woodchuck could chuck "
freq = np.value_count(string)
freq

In [ ]:
df1 = pd.DataFrame([["17","Mayank","95"],["18","Nishant","96"]],columns =["Roll no.","Name","Marks"])
df1

In [ ]:
df2 = pd.DataFrame({"Roll no.":["17","18"],"Name":["Mayank","Nishant"],"Marks":["95","96"]})
df2

In [ ]:
df.columns
df.keys()

In [ ]:
df.values

In [ ]:
df["country"].nunique()

In [ ]:
df.info?

In [ ]:
df.describe()
df

In [ ]:
df["continent"].value_counts()


In [ ]:
df.value_counts?

In [ ]:
df.rename(columns = {"country":"Country","population":"Population"})

In [ ]:
df["le/gdp"] = df["life_exp"] / df["gdp_cap"]
df

In [ ]:
df.index = [i for i in range(1,1705)]
df

In [ ]:
df

In [ ]:
s = "How much wood would a woodchuck chuck if a woodchuck could chuck" 
df5 = pd.Series(s.split(" "))
freq = df5.value_counts()
freq
freq.sort_index()
df5.index

In [ ]:
pd.Series?

In [ ]:
df.set_index("population")
df.loc["continent",:]

In [ ]:
df.insert?

# Pandas -3

In [ ]:
import pandas as pd
df =pd.read_csv("C:/Users/Lenovo/Desktop/Jupyter Notebook/gapminder.csv")

In [ ]:
df

In [ ]:
df["Sum"] = df["population"]+df["year"]+df["life_exp"]

In [ ]:
df

In [ ]:
df.head().sum()

In [ ]:
dire = pd.read_csv("C:/Users/Lenovo/Desktop/Jupyter Notebook/directors.csv",index_col= 0)
movi = pd.read_csv("C:/Users/Lenovo/Desktop/Jupyter Notebook/movies.csv")

In [ ]:
print(dire)
movi

In [ ]:
data = movi.merge(dire, left_on = "director_id",right_on = "id", how = 'inner')
data

# Panddas - 6

In [ ]:
df = pd.read_csv("C:/Users/Lenovo/Desktop/Jupyter Notebook/Pfizer_1.csv")
df

In [ ]:
df[[3]].isna()

# Data -2 ,seaborn

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
vals=[1,2,3,1,2,3,3,2,4,3,2,1,2,2,4,7]
plt.hist(vals,bins=[2,3,5,7])
plt.show()

In [ ]:
vals=[1,2,3,1,2,3,3,2,4,3,2,1,2,2,4,7]
n,bins,_ = plt.hist(vals,bins=4)
plt.show()

In [ ]:
print(n)
print(bins)

In [ ]:
a=np.array([1,2,3,4,1,2,23,1,4,2,3,1,2,3,4])
np.unique(a,return_counts=True)[1]

In [ ]:
!pip install seaborn

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
iris=sns.load_dataset("iris")
tips=sns.load_dataset("tips")

In [ ]:
s1 = sns.pairplot(data=iris)

In [ ]:
s1[0]

In [ ]:
constraint=df['cast'].apply(lambda x: str(x).split(', ')).tolist() df_new=pd.DataFrame(constraint,index=df['title']) df_new=df_new.stack() df_new=pd.DataFrame(df_new) df_new.reset_index(inplace=True) df_new=df_new[['title',0]] df_new.columns=['title','cast'] df_new[df_new['cast']=='Rupa Bhimani']
Chat
Bookmarks & Notes
Lecture 

In [ ]:
#Types of Ratings
df.head()
df_Rating = df["Rating"].fillna(df['Rating'].mode(), inplace=True)
df_Rating

In [ ]:
from scipy.stats import poisson

In [ ]:
poisson.pmf(k = 5, mu = 3)

In [ ]:
1-poisson.cdf(k = 6/2 , mu =74/8 )

In [ ]:
poisson.pmf(k =1 , mu = 2)

In [ ]:
poisson.pmf(k =0 , mu = 1)

In [ ]:
x = np.arange(0,1,0.1)
y = x**2
plt.plot(x,y, color = 'r')
plt.show()
plt.xticks(np.arange(0,1,0.1))
plt.yticks(np.arange(0,1,0.1))

In [23]:
df_check = pd.read_csv("movies.csv")
df_check

Unnamed: 0     id     budget  popularity     revenue  \
0              0  43597  237000000         150  2787965087   
1              1  43598  300000000         139   961000000   
2              2  43599  245000000         107   880674609   
3              3  43600  250000000         112  1084939099   
4              5  43602  258000000         115   890871626   
...          ...    ...        ...         ...         ...   
1460        4736  48363          0           3      321952   
1461        4743  48370      27000          19     3151130   
1462        4748  48375          0           7           0   
1463        4749  48376          0           3           0   
1464        4768  48395     220000          14     2040920   

                                         title  vote_average  vote_count  \
0                                       Avatar           7.2       11800   
1     Pirates of the Caribbean: At World's End           6.9        4500   
2                                      Spectre           6.3        4466   
3                        The Dark Knight Rises           7.6        9106   
4                                 Spider-Man 3           5.9        3576   
...                                        ...           ...         ...   
1460                            The Last Waltz           7.9          64   
1461                                    Clerks           7.4         755   
1462                                   Rampage           6.0         131   
1463                                   Slacker           6.4          77   
1464                               El Mariachi           6.6         238   

      director_id  year month       day  
0            4762  2009   Dec  Thursday  
1            4763  2007   May  Saturday  
2            4764  2015   Oct    Monday  
3            4765  2012   Jul    Monday  
4            4767  2007   May   Tuesday  
...           ...   ...   ...       ...  
1460         4809  1978   May    Monday  
1461         5369  1994   Sep   Tuesday  
1462         5148  2009   Aug    Friday  
1463         5535  1990   Jul    Friday  
1464         5097  1992   Sep    Friday  

[1465 rows x 12 columns]