In [1]:
import numpy as np
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [2]:
import math
b = (4+5)/2
math.ceil(b)

5

In [3]:
A = np.array([2, 0, 1, 9, 1, 1, 1, 0, 3, 5])

In [4]:
a = [1,2,3]
b = [4,5,6]
a+b

[1, 2, 3, 4, 5, 6]

In [5]:
np.zeros?

In [6]:
pip install scipy

In [7]:
from scipy.stats import norm
z = (67.2-65)/2.5
z

0.8800000000000011

In [8]:
norm.cdf(z)

0.8105703452232882

In [9]:
z = (53-50)/2
norm.cdf(z)

0.9331927987311419

In [10]:
import pandas as pd
import numpy as np
rbc = pd.read_csv("C:/Users/Lenovo/Desktop/Jupyter Notebook/rented_bike_count.csv")
rbc.head(2)

FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/Lenovo/Desktop/Jupyter Notebook/rented_bike_count.csv'

In [ ]:
rbc["date"] = pd.to_datetime(rbc["date"])
rbc[rbc["date"].dt.month == 4]

In [ ]:
a = [[1,2],[3,4]]
a
b = np.hstack(a)
b = [i for sublist in a for i in sublist]
#b = [i for i in sublist for sublist in a]
b = list(np.vstack(a))
b

In [ ]:
rbc = pd.read_csv("C:/Users/Lenovo/Desktop/Jupyter Notebook/rented_bike_count.csv")
rbc["date"] = pd.to_datetime(rbc["date"])
rbc.head(2)

In [ ]:
#av_r_c = rbc['temp'].groupby(rbc["date"].dt.month).apply(lambda : abs(rbc['temp'].mean)-abs(rbc['temp'].median))
#av_r_c

In [ ]:
data = {"abc" : [5,6] , "def" : [5,3], "lmn" : [0,2]}
data = {v:k for k, v in data.items()}
result = [value for (num, den), value in data.items() if num/den > 1]
print(result)

In [ ]:
r1 = [0 for i in range(3)]
result1 = [r1 for j in range(3)]
result1[0][0] = 4

r1 = [0 for i in range(3)]
result2 = [r1 for j in range(3)]
result2[1][0] = 4

print(result1, result2)

In [ ]:
df = pd.read_csv("bank_final.csv")
df.head()

In [ ]:
np.percentile(df["age"],90)
df[(df["age"]>55) & (df["marital"]=="married")].output.value_counts()
round(56/4119*100,2)

In [ ]:
a= [2,7,9,20]
b= [1,6,7,9]
c= []
for i in range(len(b)):
    row =[]
    for j in range(len(a)):
        row.append(a[j] + b[i])
    c.append(row)
c

In [ ]:
#i,j = np.meshgrid(b,a)
#c = np.meshgrid(a,b) c=a+b
#c = np.meshgrid(a,b) + c = np.meshgrid(b,a)
i,j = np.meshgrid(a,b)
c=i+j
c

In [ ]:
a = [1,2,3,4]
b=np.random.shuffle(a)
print(a,3 in a)

In [ ]:
df.head(2)

In [ ]:
#no house and personal
df[(df["housing"] == 'no') & (df["loan"]=="no")].output.value_counts()
#178
#married, entrprenaur,professional course
df[(df["marital"] == 'married') & (df["job"]=="entrepreneur") & (df["education"]=="professional.course")].output.value_counts()
#1
#age less then 39
df[(df["age"]<39)].output.value_counts()
#224
#either university or professional
df[(df["education"]=="professional.course") | (df["education"]=="university")].output.value_counts()
#65

In [ ]:
lst = [1,2,3,4,5]
print(next(x for x in lst if x%2==0))
print(filter(lambda x:x%2==0,lst),[0])
print(list(filter(lambda x:x%2==0,lst))[0])
[x for x in lst if x %2 == 0][0]
print(lst.find(lambda x:x%2 == 0))

In [ ]:
df1 = pd.DataFrame({'Click_ID':["A","B"],"Count":[200,400]})
df1.rename(columns = {"Count":"Click_Count"})
print df.columns

In [ ]:
import numpy as np
a = np.array([1,2,3,4])
type(a)
for i in a[::-1]:
    print(i)
    
b,c,d,e = a.T
b,c,d,e

In [ ]:
df = pd.read_excel("C:/Users/Lenovo/Desktop/Jupyter Notebook/State_Category_dataset.xlsx")
df.head(2)

In [ ]:
df["Date"] = pd.to_datetime(df["Date"])
df_1 = df[df["Date"].dt.year ==2022]
df_1.groupby("Category")["Dollars"].sum()

In [ ]:
df = pd.read_csv("C:/Users/Lenovo/Desktop/Jupyter Notebook/Brand_XYZ.csv")
df.head(2)

In [14]:
array = np.random.randint(1,101,size=(5,5))
array[(array>50)&(array<80)]=0
array[array!=0] =1
array

array([[1, 0, 1, 1, 1],
       [0, 1, 1, 1, 1],
       [1, 1, 0, 1, 1],
       [1, 0, 1, 1, 0],
       [1, 1, 1, 1, 1]])

In [18]:
def func(x,y):
    return (y-x)**2

res = np.vectorize(func)
print(res(np.array([1,2,3]),np.array([4,5,6])).reshape(3,-1).T)

[[9 9 9]]


In [28]:
a = np.array(range(1,11))
a.resize(10,1)
a.shape

(10, 1)